# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Nix"
license = "MIT"
licenselink = "https://github.com/LordMathis/hugo-theme-nix/blob/master/LICENSE.md"
description = "Simple theme for Hugo"
homepage = "https://github.com/LordMathis/hugo-theme-nix/"
tags = ["simple", "minimal", "unix", "terminal", "blog", "multilingual"]
features = ["blog"]
min_version = 0.20
disqusShortname = "adelzaalouk-me"
theme = "nix"
baseURL = "https://adelzaalouk.me"

[author]
  name = "Matúš Námešný"
  homepage = "https://namesny.com"

[params]
  Name = "Adel Zaalouk"
  HeaderUsername = "zanetworker"
  HeaderHostname = "adelzaalouk.me"
  About = "Product @ Red Hat | MSc | Executive MBA | CN AI Tech Lead | AI Tinkerer | Technomist"
  ProfilePicture = "profile.jpg"
  GithubID = "zanetworker"
  TwitterID = "zanetworker"
  LinkedInID = "adelzaalouk"
  SubstackURL = "https://thetechnomist.com/"
  GoogleAnalytics = "UA-90858024-1"
  CNCF="zanetworker"
  darkMode = true

[[menu.header]]
  identifier = "about"
  name = "About"
  weight = 7
  url = "/about"
[[menu.header]]
  identifier = "posts"
  name = "posts"
  weight = 9
  url = "/post"
[[menu.header]]
  parent = "posts"
  name = "tags"
  url = "/tags"
[[menu.header]]
  parent = "posts"
  name = "categories"
  url = "/categories"
[[menu.header]]
  parent = "posts"
  identifier = "kbooms"
  name = "Kbooms!"
  weight = 8
  url = "/kbooms"
[[menu.header]]
  parent = "posts"
  name = "All Posts"
  url = "/post"

[[menu.header]]
  identifier = "publications"
  name = "Publications"
  weight = 7
  url = "/publications"